# Generated by Django 3.1.2 on 2021-02-21 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210220_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='group',
        ),
        migrations.AddField(
            model_name='poll',
            name='group',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.group'),
        ),
    ]
