# Generated by Django 3.1.2 on 2021-02-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210221_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='group',
        ),
        migrations.AddField(
            model_name='poll',
            name='group',
            field=models.ManyToManyField(to='main.Group'),
        ),
    ]
