# Generated by Django 3.1.2 on 2021-02-21 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210221_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='counts',
            new_name='vote',
        ),
    ]
