# Generated by Django 3.1.2 on 2021-02-21 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210221_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.poll'),
        ),
        migrations.AlterField(
            model_name='option',
            name='vote',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
