# Generated by Django 3.1.2 on 2021-02-21 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='poll',
        ),
        migrations.AddField(
            model_name='poll',
            name='option',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.option'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='choice',
        ),
    ]
