# Generated by Django 3.1.2 on 2021-02-21 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210221_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='option',
        ),
        migrations.AddField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.poll'),
            preserve_default=False,
        ),
    ]
